### ISSUE TITLE
Failing with synthetic data in search_coarse_channel()

### ISSUE THREAD

**Issue by texadactyl** [luigifcruz/turboseti-stream#5]
python3 test_synth_signal.py
Clancy is being initialised
DEBUG drift_indexes tsteps=60, dia_num=5
DEBUG drift_indexes file_path=/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/drift_indexes/drift_indexes_array_5.txt
DEBUG drift_indexes di_array.shape: (16, 32)
DEBUG self.data_dict.tsteps - 1 - ts_mid: 29
Traceback (most recent call last):
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/test_synth_signal.py", line 29, in <module>
    clancy = DopplerFinder(filename="CH0_TIMESTAMP.h5",
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/main.py", line 145, in __init__
    drift_indexes = di_array[(self.data_dict.tsteps - 1 - ts_mid)

**Comment by texadactyl** [comment]
And this turns out to be a bug introduced in turbo_seti search_coarse_channel().

**Comment by texadactyl** [comment]
That section of main.py needs some commentary when a failure occurs!
See load_drift_indexes(self) in the turbo_seti data_handler.py

**Comment by texadactyl** [comment]
Line 234:  This only works within turbo_seti.  Needs a re-think.
