### ISSUE TITLE
Yet another crash in search_coarse_channel()

### ISSUE THREAD

**Issue by texadactyl** [luigifcruz/turboseti-stream#7]
```
python3 test_synth_signal.py
Clancy is being initialised
DEBUG drift_indexes tsteps=60, dia_num=6
DEBUG drift_indexes file_path=/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/drift_indexes/drift_indexes_array_6.txt
DEBUG drift_indexes di_array.shape: (32, 64)
DEBUG self.data_dict.tsteps - 1 - ts_mid: 29
turboseti-stream DataLoader __init__: data_obj: {'f_start': 8437.625, 'f_stop': 8441.624999, 'tsteps': 60, 'tsteps_valid': 60, 'tdwidth': 4000000, 'fftlen': 4000000, 'shoulder_size': 0, 'drift_rate_resolution': 1.666666249999859e-08, 'coarse_chan': 0, 'header': {'coarse_chan': 0, 'obs_length': 60, 'DELTAF': 9.999997499999154e-13, 'NAXIS1': 4000000, 'FCNTR': 0.0084396249995, 'baryv': 0, 'SOURCE': 'SYNTHETIC', 'MJD': 59423.2, 'RA': 7.456805, 'DEC': 5.225785, 'DELTAT': 1, 'max_drift_rate': 4.0}}
Clancy is searching for ET
turboseti-stream DataLoader load_npy_file: spectra shape: (60, 4000000)
Traceback (most recent call last):
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/test_synth_signal.py", line 41, in <module>
    clancy.find_ET_from_synth(NUMPY_PATH)
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/main.py", line 155, in find_ET_from_synth
    fd.search_coarse_channel(self.data_dict, self.find_doppler_instance, dataloader=self.dataloader)
  File "/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/find_doppler/find_doppler.py", line 427, in search_coarse_channel
    indx = ibrev[drift_indices[::-1][bool_selected][k]] * tdwidth
IndexError: index 61 is out of bounds for axis 0 with size 60
```

**Comment by texadactyl** [comment]
And its in the middle of the horror main loop with the drift index blocks:

```
            for k, drift_rate in enumerate(complete_drift_range[bool_selected]):
                # DCP 2020.04 -- WAR to drift rate in flipped files
                if data_obj.header['DELTAF'] < 0:
                    drift_rate = -drift_rate

                indx = ibrev[drift_indices[::-1][bool_selected][k]] * tdwidth  #  <----------- OUCH!

                # SEARCH NEGATIVE DRIFT RATES
                spectrum = tree_findoppler_flip[indx: indx + tdwidth]

                # Reverse spectrum back
                spectrum = spectrum[::-1]

                hitsearch(fd, spectrum, specstart, specend, snr, drift_rate, data_obj.header,
                          tdwidth, max_val, 0, the_median, the_stddev)

```

**Comment by texadactyl** [comment]
The problem is building the ```ibrev``` array:
```
    # build index mask for in-place tree doppler correction
    ibrev = fd.kernels.np.zeros(tsteps, dtype=fd.kernels.np.int32)

    for i in range(0, tsteps):
        ibrev[i] = fd.kernels.bitrev(i, int(fd.kernels.np.log2(tsteps)))

```

In a normal turbo_seti run, ibrev.shape is 64.  Somehow, in this app its only 60.

**Comment by texadactyl** [comment]
Could be a difference with setigen saving the data as a numpy array (npy) as opposed to a filterbank file?

**Comment by texadactyl** [comment]
How did tsteps get to 64 when running turbo_seti?

**Comment by wfarah** [comment]
@texadactyl we increased it from 60 to 64 to avoid the crash you mentioned

**Comment by texadactyl** [comment]
But why?
Turbo_seti handles n_ints_in_file=60 and comes up with tsteps=64.

**Comment by texadactyl** [comment]
The why is important

**Comment by texadactyl** [comment]
```
import math
import numpy as np
for tsteps_valid in range(10, 61):
    tsteps = int(math.pow(2, math.ceil(np.log2(math.floor(tsteps_valid)))))
    print(tsteps_valid, tsteps)
```

```
10 16
11 16
12 16
13 16
14 16
15 16
16 16
17 32
18 32
19 32
20 32
21 32
22 32
23 32
24 32
25 32
26 32
27 32
28 32
29 32
30 32
31 32
32 32
33 64
34 64
35 64
36 64
37 64
38 64
39 64
40 64
41 64
42 64
43 64
44 64
45 64
46 64
47 64
48 64
49 64
50 64
51 64
52 64
53 64
54 64
55 64
56 64
57 64
58 64
59 64
60 64
```
