### ISSUE TITLE
n_ints_in_file value can cause crash

### ISSUE THREAD

**Issue by texadactyl** [luigifcruz/turboseti-stream#8]
```python3 test_fake_signal.py```

n_ints_in_file=64
successfully finds the one signal.

n_ints_in_file=60
```
Creating fake signal...
Done.
Clancy's being initialised
DEBUG drift_indexes tsteps=64, dia_num=6
DEBUG drift_indexes file_path=/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/drift_indexes/drift_indexes_array_6.txt
DEBUG drift_indexes di_array.shape: (32, 64)
DEBUG self.data_dict.tsteps - 1 - ts_mid: 31
turboseti-stream DataLoader __init__: data_obj: {'f_start': 3000000000.0, 'f_stop': 3001000000.0, 'tsteps_valid': 60, 'tsteps': 64, 'tdwidth': 1000000, 'fftlen': 1000000, 'shoulder_size': 0, 'drift_rate_resolution': 0.016666666666666666, 'coarse_chan': 0, 'header': {'coarse_chan': 0, 'obs_length': 60, 'DELTAF': 1e-06, 'NAXIS1': 1000000, 'FCNTR': 3000.5, 'baryv': 0, 'SOURCE': 'test', 'MJD': 59423.2, 'RA': 7.456805, 'DEC': 5.225785, 'DELTAT': 1, 'max_drift_rate': 10.0}}
Clancy's searching for ET
turboseti-stream DataLoader load: spectra shape: (60, 1000000)
DEBUG ibrev created, ibrev.shape=(64,), tsteps=64
Traceback (most recent call last):
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/test_fake_signal.py", line 47, in <module>
    clancy.find_ET(frame.data)
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/main.py", line 197, in find_ET
    self._find_ET_common()
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/main.py", line 189, in _find_ET_common
    fd.search_coarse_channel(self.data_dict,
  File "/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/find_doppler/find_doppler.py", line 427, in search_coarse_channel
    indx = ibrev[drift_indices[::-1][bool_selected][k]] * tdwidth
IndexError: boolean index did not match indexed array along dimension 0; dimension is 64 but corresponding boolean dimension is 60
```

**Comment by texadactyl** [comment]
python3 test_synth_signal.py
```
Clancy is being initialised
DEBUG drift_indexes tsteps=64, dia_num=6
DEBUG drift_indexes file_path=/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/drift_indexes/drift_indexes_array_6.txt
DEBUG drift_indexes di_array.shape: (32, 64)
DEBUG self.data_dict.tsteps - 1 - ts_mid: 31
turboseti-stream DataLoader __init__: data_obj: {'f_start': 8437.625, 'f_stop': 8441.624999, 'tsteps_valid': 64, 'tsteps': 64, 'tdwidth': 4000000, 'fftlen': 4000000, 'shoulder_size': 0, 'drift_rate_resolution': 0.015624996093748678, 'coarse_chan': 0, 'header': {'coarse_chan': 0, 'obs_length': 64, 'DELTAF': 9.999997499999154e-07, 'NAXIS1': 4000000, 'FCNTR': 8439.6249995, 'baryv': 0, 'SOURCE': 'SYNTHETIC', 'MJD': 59423.2, 'RA': 7.456805, 'DEC': 5.225785, 'DELTAT': 1, 'max_drift_rate': 10.0}}
Clancy is searching for ET
turboseti-stream DataLoader load_file: spectra shape: (60, 4000000)
DEBUG ibrev created, ibrev.shape=(64,), tsteps=64
Traceback (most recent call last):
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/test_synth_signal.py", line 42, in <module>
    clancy.find_ET_from_file(INFILE)
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/main.py", line 201, in find_ET_from_file
    self._find_ET_common()
  File "/home/elkins/BASIS/seti_testing/turboseti-stream-main/main.py", line 189, in _find_ET_common
    fd.search_coarse_channel(self.data_dict,
  File "/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/find_doppler/find_doppler.py", line 404, in search_coarse_channel
    populate_tree(fd, spectra, tree_findoppler, nframes, tdwidth, tsteps, fftlen, shoulder_size,
  File "/usr/local/lib/python3.9/dist-packages/turbo_seti-2.1.10-py3.9.egg/turbo_seti/find_doppler/find_doppler.py", line 532, in populate_tree
    fd.kernels.xp.copyto(tree_findoppler[sind_a:sind_a+fftlen], fd.kernels.xp.roll(spectra[i], roll * i * direction))
IndexError: index 60 is out of bounds for axis 0 with size 60

```

**Comment by texadactyl** [comment]
turboSETI on the same spectra.fil file:
```
turboSETI /tmp/spectra.fil -o /tmp

turbo_seti version 2.1.10
blimpy version 2.0.19
h5py version 3.3.0

data_handler    INFO     Filterbank file detected. Attempting to create .h5 file in current directory...
blimpy.waterfall INFO     Detecting high frequency resolution data.
blimpy.waterfall INFO     Using 1 n_blobs to write the data.
blimpy.waterfall INFO     Reading 1 of 1
HDF5 header info: {'DIMENSION_LABELS': array(['time', 'feed_id', 'frequency'], dtype=object), 'az_start': 0.0, 'data_type': 1, 'fch1': 8437.625, 'foff': 1e-06, 'ibeam': -1, 'machine_id': 20, 'nbeams': 1, 'nbits': 32, 'nchans': 4000000, 'nifs': 1, 'rawdatafile': 'Synthetic', 'source_name': 'Synthetic', 'src_dej': <Angle -28.3831 deg>, 'src_raj': <Angle 17.7875 hourangle>, 'telescope_id': 6, 'tsamp': 1.0, 'tstart': 58465.717094907406, 'za_start': 0.0}

Starting ET search with parameters: datafile=/tmp/spectra.fil, max_drift=10.0, min_drift=1e-05, snr=25.0, out_dir=/tmp, coarse_chans=, flagging=False, n_coarse_chan=1, kernels=None, gpu_id=0, gpu_backend=False, blank_dc=True, precision=1, append_output=False, log_level_int=20, obs_info={'pulsar': 0, 'pulsar_found': 0, 'pulsar_dm': 0.0, 'pulsar_snr': 0.0, 'pulsar_stats': array([0., 0., 0., 0., 0., 0.]), 'RFI_level': 0.0, 'Mean_SEFD': 0.0, 'psrflux_Sens': 0.0, 'SEFDs_val': [0.0], 'SEFDs_freq': [0.0], 'SEFDs_freq_up': [0.0]}

Computed drift rate resolution: 0.016666666666666666

DEBUG ibrev created, ibrev.shape=(64,), tsteps=64
find_doppler.0  INFO     Top hit found! SNR 91.134613, Drift Rate 1.383333, index 800000
find_doppler.0  INFO     Top hit found! SNR 363.774872, Drift Rate 4.150000, index 1333333
find_doppler.0  INFO     Top hit found! SNR 226.736374, Drift Rate -2.766667, index 3200000
Search time:  0.74 min

```

**Comment by texadactyl** [comment]
No longer crashes

**Comment by wfarah** [comment]
What was the issue, @texadactyl ?

**Comment by texadactyl** [comment]
There was a mistake in main.py in computing the drift_indexes array.  It was based on my misunderstanding of the relationship between tsteps and tsteps_valid.  They are not the same.
